plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation "net.blay09.mods:trashslot-fabric:${trashslot_fabric_version}"
    implementation "net.blay09.mods:balm-fabric:${balm_fabric_version}"
}

repositories {
    maven {
        name = 'TwelveIterations'
        url = 'https://maven.twelveiterations.com/repository/maven-public/'
        content {
            includeGroup 'net.blay09.mods'
            includeGroup 'net.fabricmc'
            includeGroup 'net.fabricmc.fabric-api'
        }
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'WispForest'
        url = 'https://maven.wispforest.io'
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
