version=1.0.3
group=com.putzwirk
java_version=21

minecraft_version=1.21.1
mod_name=Trashslotblacklist
mod_author=Putzwirk
mod_id=trashslotblacklist
license=MIT
credits=
description=Trashslotblacklist by Putzwirk.
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

forge_version=52.0.28
forge_loader_version_range=[52,)

neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
