version=1.0.3
group=com.putzwirk
java_version=25

minecraft_version=26.2
mod_name=Trashslotblacklist
mod_author=Putzwirk
mod_id=trashslotblacklist
license=MIT
credits=
description=Trashslotblacklist by Putzwirk.
minecraft_version_range=[26.2]
neo_form_version=26.2-2

fabric_version=0.158.0+26.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

balm_fabric_version=26.2.0.7
balm_neoforge_version=26.2.0.7
trashslot_fabric_version=26.2.0.1
trashslot_neoforge_version=26.2.0.1

neoforge_version=26.2.0.72
neoforge_loader_version_range=[11,)
moddev_version=2.0.144

forge_version=63.0.2
forge_loader_version_range=[63,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
